### ISSUE TITLE
Hide the Key Field

### ISSUE THREAD

**Issue by MidnQP** [ivan-sincek/chat-app#2]
Please have something like show/hide Key?

**Comment by ivan-sincek** [comment]
Hi,

Thank you for your suggestion.

I will look into it and implement the feature in near future.

Best regards,
Ivan.

**Comment by ivan-sincek** [comment]
Done!

Best regards,
Ivan.

**Comment by MidnQP** [comment]
Would you please pay a visit: http://github.com/midnqp/TerminalChat ?

I've trying to do everything in the command prompt. Things can be improved - I recognize the fact.

**Comment by MidnQP** [comment]
Also, please let me know thoughts on http://github.com/midnqp/multi-code
http://github.com/midnqp/cpy
