### ISSUE TITLE
How to Make a Client Interact With Another Client?

### ISSUE THREAD

**Issue by jr0driguezv** [ivan-sincek/chat-app#5]
Hello, thanks for your contribution, I find it interesting and with a not very complex code.

There is the possibility of using this chat, so that a client can communicate with another client, so that it is properly a chat as it commonly exists, that the user can select which user of those who are connected to send a message, and that this message is show that specific user and interact with each other.

How could I do that? It would be a lot of annoyance if you make a sample in this way, I would be very grateful, thank you ...

**Comment by ivan-sincek** [comment]
Hi,

Thank you for the suggestion.

If I understood correctly, you would like me to add the option to send private/direct messages; where server would just list active users/clients, and the users would connect with each other directly?

I am afraid this is a bit out of my current scope. This is just a college project I did few years ago, and my goal was to show multithreading and asynchronous read and write, and nothing more.

Though, I will add this to my "to do" list, but won't be anytime soon, sorry.

Best regards,
Ivan.

**Comment by jr0driguezv** [comment]
Hello Ivan

Thank you for taking the time to respond, I understand, no problem, I know that each person has their commitments and things to do that greatly limit the time available.

**Comment by yigitoner28** [comment]
Hello Ivan, your TCP IP project is great, I would like you to know that. I have only one question, I have an android client application from the extra, whenever I connect to the server and click send without typing anything, a null exception comes up. How can I solve this? Thank you for your interest👍
